config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'
  #get means rails mapsrequests to localhost:3000/welcome/index to the index action
  root 'welcome#index'
  #root means rails maps requests to the root (localhost:3000) to the index action

  #extra webpages not associated with resources
  get 'welcome/tutorial'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'logout', to: 'sessions#destroy'

  post 'games/add_ai', to: 'games#add_ai'
  post 'games/add_player', to: 'games#add_player'
  post 'games/action', to: 'games#action' #bet, fold, check, etc.
  post 'games/move_card', to: 'games#move_card'
  post 'games/deal', to: 'games#deal'
  post 'games/set_round', to: 'games#set_round'
  post 'games/leave_game', to: 'games#leave_game'
  post 'games/start_game', to: 'games#start_game'
  post 'games/ai_play', to: 'games#ai_play'

  #created by andrew while learning rails 2/13, see app/controllers/cards_controller.rb
  resources :games
  resources :cards
  resources :users
  resources :players
  #resources method, used to declare a standard REST resource, provides many routes

end

app/models/game.rb
class Game < ApplicationRecord
  has_many :players, dependent: :destroy
  has_many :cards, dependent: :destroy

  #gets a random card from the deck
  def get_random_card
    return self.cards.where(:location => -1)[rand(self.cards.where(:location => -1).length)]
  end

  def init
    self.round = 4
    ranks = ['A', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K']
    suits = ['S', 'H', 'C', 'D']
    self.pot = 0
    self.dealer = 10
    self.big_blind = 2
    self.small_blind = 1
    self.high_bet = -1
    self.high_better = -1
    ranks.collect do |rank|
      suits.collect do |suit|
        self.cards << Card.new({:game_id => self.id, :rank => rank, :suit => suit, :location => -1})
        self.save
      end
    end
  end

  # called at the start of each round to deal and reset round specific values
  def deal(round)
    round_int = round.to_i
    case round_int
    when 0
      self.players.each do |player|
        move_card(get_random_card, player.location)   # moves cards to users
        move_card(get_random_card, player.location)
        # player.in_hand = true
        player.save
      end
      addBlinds()
    when 1
      self.current_player = get_next_player(self.dealer)
      move_card(get_random_card, 0)  #moves cards to table
      move_card(get_random_card, 0)
      move_card(get_random_card, 0)
    when 2
      self.current_player = get_next_player(self.dealer)
      move_card(get_random_card, 0)
    when 3
      self.current_player = get_next_player(self.dealer)
      move_card(get_random_card, 0)
    when 4
      get_winners()
    else
      p 'deal case > 4 or < 0, error'
    end

    self.players.each do |player|
      player.in_pot_current = 0
      player.save
    end
    if round_int > 0 && round_int < 4
      self.high_bet = 0
      self.high_better = self.current_player
    end
    self.save
  end

  # helper function that puts blinds in pot upon dealing cards in first round of game
  # sets first player to person after big blind
  def addBlinds()
    s_blind_loc = get_next_player(self.dealer) # location of small blind player
    b_blind_loc = get_next_player(s_blind_loc) # location of big blind player
    # get player data for small and big blind locations
    s_blind_player = get_player(s_blind_loc)  # actual players to change money
    b_blind_player = get_player(b_blind_loc)
    # put money from small and big blind players into pot
    put_money(self.small_blind, s_blind_player)
    put_money(self.big_blind, b_blind_player)
    self.current_player = get_next_player(b_blind_loc)
    b_blind_player.save
    s_blind_player.save
    self.save
  end

  #puts money in pot and updates associated values
  def put_money(amount, player)
    if amount > player.money
      amount = player.money
    end
    if amount + player.in_pot_current > self.high_bet   # if player is new high bet (bets more than current highest)
      self.high_bet = amount + player.in_pot_current
      self.high_better = player.location
    end
    player.money -= amount    # puts money in correct places and takes from player's pot
    player.in_pot_current += amount
    player.in_pot_hand += amount
    self.pot += amount
    player.save
    self.save
  end

  # handles player actions
  # progresses current_player
  # progresses round if a round has completed
  def action(type, amount, player)
    @player = Player.find(player.to_i)
    amount = amount.to_i
    case type
    when 'fold'
      @player.in_hand = false
    when 'bet'
      if amount > @player.money
        amount = @player.money
      end
      if amount + @player.in_pot_current < self.high_bet
        p 'invalid bet'
      else
        put_money(amount, @player)
      end
    when 'raise'
      # If player doesn't have enough money or trying to not raise enough and can't bet enough
      if amount > @player.money || (amount + @player.in_pot_current < 2*self.high_bet && 2*self.high_bet - @player.in_pot_current > @player.money)
        amount = @player.money
      elsif amount + @player.in_pot_current < self.high_bet
        amount = 2*self.high_bet - @player.in_pot_current
      else
        amount = amount + self.high_bet - @player.in_pot_current
      end
      put_money(amount, @player)
    when 'check'
      # do nothing; high better already set to be player after dealer inside of deal()
    when 'call'
      amount = self.high_bet - @player.in_pot_current
      put_money(amount, @player)
    else
      p 'invalid action'
    end
    self.current_player = self.get_next_player(@player.location) # Set next player to current

    @player.save
    self.save
    if self.high_better == self.current_player #progress round if you've gone back around to the high better
      # unless no one raises and it's back to big blind, bb should be able to go
      if self.high_bet <= self.big_blind && self.round == 0 && self.high_better == get_next_player(get_next_player(self.dealer))
        self.high_better = get_next_player(get_next_player(get_next_player(self.dealer)))
      else
        set_round((self.round + 1))
        deal(self.round)
      end
    end
    if self.players.where(:in_hand => true).length <= 1
      set_round(4)
    end

    @player.save
    self.save
  end

  # Set of helper functions that check if player actions are valid
  def can_call?(player)
    return (self.high_bet > player.in_pot_current)
  end
  def can_check?(player)
    return (self.high_bet == player.in_pot_current)
  end
  def can_bet?(player)
    return (self.high_bet == 0) #todo: enforce min bet
  end
  def can_raise?(players) #todo: enforce min raise
    return (self.high_bet != 0)
  end

  # Gets called from deal(4)
  def end_game()
    get_winners()
  end

  def ai_turn?()
    return get_player(self.current_player).ai != ""
  end

  # takes actions for the AI that is up
  def ai_action()
    # sleep 3
    player = get_player(self.current_player)
    action_info = ai_one_logic(player)
    if player.ai == "2"
      action_info = ai_two_logic(player)
    end
    action(action_info[0], action_info[1], player.id) # this progresses current player and may progress round
    self.save
  end

  # Defines a basic AI, giving them actions to take under different conditions
  def ai_one_logic(player)
    type = player.ai
    if self.round == 0
      if self.high_bet < 5
        return 'call', 0
      else
        return 'fold', 0
      end
    else
      if self.high_bet == 0
        return 'bet', 2
      elsif self.high_bet < 4
        return 'raise', 4
      elsif self.high_bet >= 16
        return 'fold', 0
      else
        return 'call', 0
      end
    end
  end

  def ai_two_logic(player)
    type = player.ai
    probjudge = Probjudge.new(self.cards.where(:location => player.location), self.cards.where(:location => 0))
    prob = probjudge.judge()
    maxBet = (self.round * 5 * prob) + 5
    if self.round == 0
      if self.high_bet < 5
        return 'call', 0
      else
        return 'fold', 0
      end
    else
      if self.high_bet == 0
        return 'bet', maxBet / 2
      elsif self.high_bet < maxBet / 2
        return 'raise', (maxBet / 2) - self.high_bet
      elsif self.high_bet < maxBet
        return 'call', 0
      else
        return 'fold', 0
      end
    end
  end

  # locations are deck, table, or players
  def move_card(card, destination)
    card.location = destination
    card.save
  end

  def get_winners()
    scoreToString = {1=>'High Card', 2=>'Pair', 3=>'Two Pair', 4=>'Three of a Kind', 5=>'Straight', 6=>'Flush', 7=>'Full House', 8=>'Four of a Kind', 9=>'Straight Flush', 10=>'Royal Flush'}
    high_score = -100^7
    winners = []
    players_in_hand = self.players.where(:in_hand => true)
    players_in_hand.each do |player|
      cards = self.cards.where(:location => player.location) + self.cards.where(:location => 0)
      if cards.length() == 7
        handjudge = Handjudge.new(cards)
        player.score = handjudge.judge()
        p 'score:'
        p player.score
        player.hand = scoreToString[(player.score.to_f/(100**5)).round()]
        player.save
        if player.score > high_score
          high_score = player.score
          winners = [player]
        elsif player.score == high_score
          winners.append(player)
        end
      else
        p 'invalid number of cards passed'
        return players_in_hand
      end
    end
    return winners
  end


  # At the end of a game, this is called to reset card deck (by button), correctly allocate the round's money,
  # and increment the dealer
  def reset_game()
    # If money in pot, distribute
    while (self.pot > 0)
      winners = []
      # In case where everyone has folded, set the winner to whoever is left
      if self.players.where(:in_hand => true).length <= 1
        winners = self.players.where(:in_hand => true)
      else
        #gets people with highest score
        winners = get_winners()
      end
      winners.each do |winner|
        #TO IMPLEMENT: more advanced side pots
        winner.money += self.pot / winners.length()
        winner.save
      end
      self.pot = 0
    end
    # reset deck of cards
    self.cards.where.not(:location => -1).each do |card|
      card.location = -1
      card.save
    end
    # reset amount each player has in the pot to 0
    self.players.each do |player|
      player.in_hand = true
      player.in_pot_hand = 0
      player.in_pot_current = 0
      player.hand = ''
      player.save
    end
    # reset pot to empty, increment dealer if not first hand
    if self.round != -1
      self.dealer = (self.dealer + 1)%10 + 10
    end
    # makes sure a player exists where the dealer is set
    while self.players.where(:location => self.dealer).length == 0
      self.dealer = (self.dealer + 1)%10 + 10
    end
    self.round = 0
    self.high_bet = 0
    self.high_better = get_next_player(self.dealer)
    self.save
    deal(self.round)
  end

  def set_round(round)
    p 'advanced game round to '
    p round

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]


  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  # TODO: move game logic
  def show

  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.create(game_params)
    @game.init
    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.players.each do |p|
      p.destroy
    end

    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def add_ai
    Game.find_by(id: params[:game]).add_ai_player(params[:type], User.find_by(id: params[:user].to_i))
    redirect_back(fallback_location: root_path)
  end
  def add_player
    Game.find_by(id: params[:game]).add_user_player(User.find_by(id: params[:user].to_i))
    redirect_back(fallback_location: root_path)
  end
  def move_card
    Game.find(params[:game]).move_card(Card.find(params[:card]), params[:destination])
    redirect_back(fallback_location: root_path)
  end
  def action
    Game.find_by(id: params[:game]).action(params[:type], params[:amount], params[:player])
    redirect_back(fallback_location: root_path)
  end
  def deal
    Game.find_by(id: params[:game]).deal(params[:round])
    redirect_back(fallback_location: root_path)
  end
  def set_round
    Game.find_by(id: params[:game]).set_round(params[:round])
    redirect_back(fallback_location: root_path)
  end
  def leave_game
    Game.find_by(id: params[:game]).leave_game(params[:player])
    redirect_back(fallback_location: root_path)
  end
  def start_game
    Game.find_by(id: params[:game]).reset_game()
    redirect_back(fallback_location: root_path)
  end
  def ai_play
    Game.find_by(id: params[:game]).ai_action()
    redirect_back(fallback_location: root_path)
  end

  def action_loop(id)
    while Game.find_by(id: params[:game]).ai_turn?
      Game.find_by(id: params[:game]).ai_action()
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end
    # Only allow a list of trusted parameters through.
    def game_params
      params.require(:game).permit(:room_name)
    end
end

app/helpers/games_helper.rb
module GamesHelper
  def get_player(user, game)

    return game.players.where(:user => user, :ai => "")[0]
  end
  def get_players_cards(player, game)
    return game.cards.where(:location.to_s => player.location.to_s)
  end
  def get_table_cards(game)
    return game.cards.where(:location.to_s => 0)
  end
  def get_random_card(game)
    return game.cards.where(:location => -1)[rand(game.cards.where(:location => -1).length)]
  end
  def in_game(user, game)
    return get_player(user, game)
  end

end

app/views/games/_form.html.erb
<%= form_with(model: game, local: true) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
        <% game.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :room_name %>
    <%= form.text_field :room_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Games</h1>
<div class="container">
  <div class="table">
    <div class="table-header">
      <div class="header__item"> room name </div>
      <div class="header__item"> players </div>
      <div class="header__item"> </div>
      <div class="header__item"> </div>
      <div class="header__item"> </div>
    </div>
    <% @games.each do |game| %>
      <div class="table-row">
        <div class='table-data'> <%= game.room_name %></div>
        <div class='table-data'> <%= game.players.length %></div>
        <div class='table-data'> <%= link_to 'Show', game%></div>
        <div class='table-data'> <%= link_to 'Edit', edit_game_path(game) %></div>
        <div class='table-data'> <%= link_to 'Destroy', game, method: :delete, data: {confirm: 'Are you sure you would like to delete this game?' }%></div>
      </div>
    <%end%>
  </div>
</div>



<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<strong>Room name:</strong>
<%= @game.room_name %>

<% if @game.round > 0 %>
  <center><h2>Table Cards</h2></center>
<% end %>
<div class="card-container">
  <div class="row">
    <% get_table_cards(@game).each do |card| %>
      <% card_str = card.rank + card.suit %>
      <img src="/assets/cards/<%= card_str %>.png">
    <%end%>
  </div>
  <div class="row">
    <b><font size="+1">
      <font color='000000'>
        <div class="text-box">
          Pot: $<%= @game.pot %>
        </div>
      </font>
    </font></b>
  </div>
  <div class="row">
    <b><font color='000000'>
      <div class="text-box">
        High bet: $<%= @game.high_bet %>
      </div>
    </font></b>
  </div>
  <br/>
  <div class = "row">
    <% @game.players.each do |player| %>
      <% player_name = player.username %>
      <% if player.location == @game.dealer %>
        <% player_name += " (dealer)" %>
      <%end%>
      <% if @game.current_player == player.location && @game.round != 4 %>
        <b><font color='bb1111'><div class="text-box"><%= player_name %></div></font></b>
      <% else %>
        <div class="text-box"><%= player_name %></div>
      <%end%>
    <%end%>
  </div>
  <div class = "row">
    <% @game.players.each do |player| %>
      <div class="text-box">
        Bank: $<%= player.money %>
      </div>
    <% end %>
  </div>
  <div class = "row">
    <% @game.players.each do |player| %>
      <% if player.ai != "" && (@game.round < 4 or player.in_hand==false) %>
        <div class = "overlap">
          <div class = "overlap-container"><img src="/assets/cards/green_back.png"></div>
          <div class = "overlap-container"><img src="/assets/cards/green_back.png"></div>
        </div>
      <% else %>
        <div class = "overlap">
          <% get_players_cards(player, @game).each do |card| %>
            <% card_str = card.rank + card.suit %>
            <div class = "overlap-container"><img src="/assets/cards/<%= card_str %>.png"></div>
          <%end%>
        </div>
      <%end%>
    <%end%>
  </div>
  <div class="row">
  <% if @game.round != 4 %>
    <% @game.players.each do |player| %>
      <% bet = "$" + player.in_pot_current.to_s %>
      <% if player.in_hand == false %>
        <% bet = "Folded" %>
      <%end%>
      <div class="text-box">Bet: <%= bet %></div>
    <%end%>
  <% else %>
    <% winners = @game.get_winners() %>
    <% @game.players.each do |player| %>
      <% if player.in_hand == false %>
        <div class="text-box">Folded</div>
      <% elsif winners.include?(player) %>
        <b><div class="text-box"><%= player.hand %></div></b>
      <% else %>
        <div class="text-box"><%= player.hand %></div>
      <% end %>
    <% end %>
  <% end %>
  </div>
  <div class="row">
    <% @game.players.each do |player| %>
      <div class="text-box">In pot: $<%= player.in_pot_hand %></div>
    <%end%>
  </div>
</div>

<% if in_game(current_user, @game) %>
  <% if @game.round == 4 %>
    <%= button_to 'start next hand', 'start_game', params:{game: @game.id} %>
  <% end %>
<%end%>

<br/>

<% if in_game(current_user, @game) %>
  <% if get_player(current_user, @game).location == @game.current_player && @game.round < 4 %>
    <%if @game.can_call?(get_player(current_user, @game)) %>
      <%= button_to 'Call', 'action', params:{game: @game.id, type: 'call', player: get_player(current_user, @game)} %> <%end%>
    <%if @game.can_check?(get_player(current_user, @game)) %>
      <%= button_to 'Check', 'action', params:{game: @game.id, type: 'check', player: get_player(current_user, @game)} %> <%end%>
    <%if @game.can_bet?(get_player(current_user, @game)) %>
      <%= form_with(url: "action", method: 'post') do %>
        <%= hidden_field_tag(:game, @game.id) %>
        <%= hidden_field_tag(:type, 'bet') %>
        <%= hidden_field_tag(:player, get_player(current_user, @game).id) %>
        <%= number_field_tag(:amount) %>
        <%= submit_tag("Bet") %>
      <% end %> <% end %>
    <%if @game.can_raise?(get_player(current_user, @game)) %>
      <%= form_with(url: "action", method: 'post') do %>
        <%= hidden_field_tag(:game, @game.id) %>
        <%= hidden_field_tag(:type, 'raise') %>
        <%= hidden_field_tag(:player, get_player(current_user, @game).id) %>
        <%= number_field_tag(:amount) %>
        <%= submit_tag("Raise") %>
      <% end %>
    <% end %>
    <%= button_to 'Fold', 'action', params:{game: @game.id, type: 'fold', player: get_player(current_user, @game)} %>
  <% elsif @game.round < 4 %>
    <%= button_to 'let ai play', 'ai_play', params:{game: @game.id} %>
    <br/><br/>
  <% end %>
<%end%> <br/>

<% if @game.round == 4 %>
  <%= button_to 'Add AI 1', 'add_ai', params:{game: @game.id, type: '1', user: current_user} %>
  <%= button_to 'Add AI 2', 'add_ai', params:{game: @game.id, type: '2', user: current_user} %>
<% end %>
<% if !in_game(current_user, @game) %>
  <%= button_to 'Join Game', 'add_player', params:{game: @game.id, user: current_user } %>
<% else %>
  <%= button_to 'Leave Game', 'leave_game', params:{game: @game.id, player: get_player(current_user, @game)}%>
<%end%>

<%= link_to 'Settings', edit_game_path(@game) %>