config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'
  #get means rails mapsrequests to localhost:3000/welcome/index to the index action
  root 'welcome#index'
  #root means rails maps requests to the root (localhost:3000) to the index action

  #extra webpages not associated with resources
  get 'welcome/tutorial'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'logout', to: 'sessions#destroy'

  post 'games/add_ai', to: 'games#add_ai'
  post 'games/add_player', to: 'games#add_player'
  post 'games/action', to: 'games#action' #bet, fold, check, etc.
  post 'games/move_card', to: 'games#move_card'
  post 'games/deal', to: 'games#deal'
  post 'games/set_round', to: 'games#set_round'
  post 'games/leave_game', to: 'games#leave_game'
  post 'games/start_game', to: 'games#start_game'
  post 'games/ai_play', to: 'games#ai_play'

  #created by andrew while learning rails 2/13, see app/controllers/cards_controller.rb
  resources :games
  resources :cards
  resources :users
  resources :players
  #resources method, used to declare a standard REST resource, provides many routes

end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :game
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def card_params
      params.require(:card).permit(:suit, :rank, :location, :game_id)
    end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_form.html.erb
<%= form_with(model: card, local: true) do |form| %>
  <% if card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
        <% card.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :suit %>
    <%= form.text_field :suit %>
  </div>

  <div class="field">
    <%= form.label :rank %>
    <%= form.text_field :rank %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :game_id %>
    <%= form.number_field :game_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1>Editing Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cards</h1>

<div class='container'>
<table>
  <thead>
    <tr>
      <th>Suit</th>
      <th>Rank</th>
      <th>Location</th>
      <th>Game</th>
      <th> </th>
      <th> </th>
      <th> </th>
    </tr>
  </thead>

  <tbody>
    <% @cards.each do |card| %>
      <tr>
        <td><%= card.suit %></td>
        <td><%= card.rank %></td>
        <td><%= card.location %></td>
        <td><%= card.game_id %></td>
        <td><%= link_to 'Show', card %></td>
        <td><%= link_to 'Edit', edit_card_path(card) %></td>
        <td><%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

<%= link_to 'New Card', new_card_path %>

app/views/cards/new.html.erb
<h1>New Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Suit:</strong>
  <%= @card.suit %>
</p>

<p>
  <strong>Rank:</strong>
  <%= @card.rank %>
</p>

<p>
  <strong>Location:</strong>
  <%= @card.location %>
</p>

<p>
  <strong>Game:</strong>
  <%= @card.game_id %>
</p>

<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Back', cards_path %>